title: Pasindu Ranawakage
email: pasindudeshitha123@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://KaSaNaa.github.io/MinimalistPortfolio" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: johndoe
github_username:  johndoe

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed